/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AmongComponent: typeof import('./src/components/layout/AmongComponent.vue')['default']
    ConfirmCom: typeof import('./src/components/render/ConfirmCom.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    LeftComponent: typeof import('./src/components/layout/LeftComponent.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    LoadingCom: typeof import('./src/components/render/LoadingCom.vue')['default']
    LoadingComponent: typeof import('./src/components/loading/LoadingComponent.vue')['default']
    LoginCom: typeof import('./src/components/login/LoginCom.vue')['default']
    LoginComponent: typeof import('./src/components/login/LoginComponent.vue')['default']
    RegisterCom: typeof import('./src/components/login/RegisterCom.vue')['default']
    RightComponent: typeof import('./src/components/layout/RightComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopComponent: typeof import('./src/components/layout/TopComponent.vue')['default']
    TopView: typeof import('./src/components/layout/TopView.vue')['default']
  }
}
